name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: 1.19.5

    - name: verify modules
      run: go mod verify

    - name: set release version env var
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: build tools
      run: |
        make

    - name: fix build artifacts
      run: |
        mv _output/skiprange skiprange-${{ env.RELEASE_VERSION }}-linux-amd64

    - name: compute signature
      run: |
        pushd _output && sha256sum * >> ../SHA256SUMS && popd

    - name: create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "SHA256SUMS,*-v*-linux-amd64"
        token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
